package personalizacion_grafica;

import java.io.BufferedReader;
import java.io.FileReader;
import java.io.IOException;
import java.util.Map;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;
import proyectoprogramacion.Juegos;

/**
 *
 * @author estudios
 */
public class Tabla extends javax.swing.JFrame {
    Sesion s= new Sesion();
    public Administrar admin= new Administrar();
    private final DefaultTableModel modeloTabla;

    /**
     * Creates new form Tabla
     */
    public Tabla() {
        modeloTabla = new DefaultTableModel();
        initComponents();
        modeloTabla.addColumn("código");
        modeloTabla.addColumn("nombre");
        modeloTabla.addColumn("tipo");
        modeloTabla.addColumn("consola");
        modeloTabla.addColumn("precio");
        modeloTabla.addColumn("dlc");
        modeloTabla.addColumn("estado");
        modeloTabla.addColumn("unidades");
        this.tabla.setModel(modeloTabla);

    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jScrollPane1 = new javax.swing.JScrollPane();
        tabla = new javax.swing.JTable();
        Mostrar = new javax.swing.JButton();
        jButton1 = new javax.swing.JButton();
        busqueda = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        tabla.setModel(modeloTabla);
        jScrollPane1.setViewportView(tabla);

        Mostrar.setText("Mostrar");
        Mostrar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                MostrarActionPerformed(evt);
            }
        });

        jButton1.setText("Inicio");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });

        busqueda.setText("Búsqueda");
        busqueda.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                busquedaActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(102, 102, 102)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(busqueda)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(Mostrar)
                        .addGap(122, 122, 122)
                        .addComponent(jButton1))
                    .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 453, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(163, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 122, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 111, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(Mostrar)
                    .addComponent(jButton1)
                    .addComponent(busqueda))
                .addGap(29, 29, 29))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void MostrarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_MostrarActionPerformed
        try {
            mostrar();
        } catch (IOException ex) {
            Logger.getLogger(Tabla.class.getName()).log(Level.SEVERE, null, ex);
        }
    }//GEN-LAST:event_MostrarActionPerformed

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        inicio();
    }//GEN-LAST:event_jButton1ActionPerformed

    private void busquedaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_busquedaActionPerformed
       buscar();
    }//GEN-LAST:event_busquedaActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException | InstantiationException | IllegalAccessException | javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Tabla.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(() -> {
            new Tabla().setVisible(true);
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton Mostrar;
    private javax.swing.JButton busqueda;
    private javax.swing.JButton jButton1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTable tabla;
    // End of variables declaration//GEN-END:variables

    private void mostrar() throws IOException {
        String line = "";
        // String[] sep, sep2;
        String[] sep = new String[7];
        String[] sep2 = new String[2];

        final BufferedReader reader;

        reader = new BufferedReader(new FileReader("JUEGOS.txt"));

        while ((line = reader.readLine()) != null) {
            Object[] linea = new Object[8];
            for (int i = 0; i < sep.length; i++) {
                sep = line.split(",");
                for (int j = 0; j <= i; j++) {
                    if (j > 0) {
                        sep2 = sep[i].split("\\s*:");
                    } else {
                        sep2 = sep[i].split(":\\s*");
                    }
                    if (i == 0) {
                        linea[0] = sep2[0];
                    }
                    if (i == 1) {
                        linea[1] = sep2[1];
                    }
                    if (i == 2) {
                        linea[2] = sep2[1];
                    }
                    if (i == 3) {
                        linea[3] = sep2[1];
                    }
                    if (i == 4) {
                        linea[4] = sep2[1];
                    }
                    if (i == 5) {
                        linea[5] = sep2[1];
                    }
                    if (i == 6) {
                        linea[6] = sep2[1];
                    }
                    if (i == 7) {
                        linea[7] = sep2[1];
                    }
                }
            }
            modeloTabla.addRow(linea);
        }
        reader.close();
    }

    private void inicio() {

        this.setVisible(false);
        s.setVisible(true);
    }

    private void buscar() {
        int buscar=Integer.parseInt(JOptionPane.showInputDialog("¿Qué código desea búscar?"));
//        Juegos j2=admin.mapaJuegos.get(buscar);
        System.out.println(admin.mapaJuegos);
        System.out.println(admin.mapaJuegos.get(buscar));
    }
}
